- name: Deploy PetCareApp Docker container
  hosts: localhost
  tasks:
    - name: Build Docker image
      command: docker build -t petcareapp .

    - name: Run Docker container
      command: docker run -d -p 8080:80 --name petcarecontainer petcareapp
